on: push
name: Curl Proxy
jobs:
    trigger_proxy:
        uses: ./.github/workflows/start_proxy.yml
    curl_proxy:
        runs-on: ubuntu-latest
        needs: trigger_proxy
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Test Proxy with Curl
          run: |
            sleep 5  # Wait for the server to start
            curl http://127.0.0.1:8080/  # Replace with your test endpoint