on: push
name: Curl Proxy
jobs:
    test_proxy:
        runs-on: windows-2022
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        
        - name: Install dependencies
          shell: pwsh
          run: |
            cd proxy_mock
            pip install -r requirements.txt
        
        - name: Start Python script in background
          shell: pwsh
          run: |
            Start-Process -NoNewWindow -FilePath "python" -ArgumentList "proxyserver.py"
            Start-Process -WindowStyle Hidden -FilePath "python" -ArgumentList "proxyserver.py"
        
        - name: Wait for server to start and verify
          shell: bash
          run: |
            echo "Waiting for proxy server to start..."
            sleep 10
        
        - name: Test Proxy with Curl
          shell: bash
          run: |
            echo "Testing proxy server connection..."
            # Test basic connectivity first
            curl -v --connect-timeout 10 --max-time 30 http://127.0.0.1:8080/ || (echo "Proxy server test failed" && exit 1)
            echo "Proxy server test passed!"
        
        - name: Test with qa web dev env
          shell: bash
          run: |
            echo "Testing qa web dev server connection..."
            # Test basic connectivity first
            curl -v --connect-timeout 10 --max-time 30 https://agentsapi-dev-qaweb.healthcare.barco.com/ || (echo "qa web dev server test failed" && exit 1)
            echo "qa web dev server test passed!"
                
        - name: Stop Proxy Server
          shell: bash
          if: always()
          run: |
            echo "Stopping proxy server..."
